apiVersion: v1
kind: Service
metadata:
  name: sqllite-service
  namespace: 
spec:
  selector:
    app: sqlitedb
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
