apiVersion: v1
kind: Service
metadata:
  name: maintenance
  namespace: 
  labels:                           # Added labels section
    app: maintenance
    namespace: 
spec:
  selector:
    app: maintenance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: NodePort
