apiVersion: v1
kind: Service
metadata:
  name: record
  namespace: 
  labels:                           # Added labels section
    app: record 
    namespace: 
spec:
  selector:
    app: record
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort

