apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: 
  labels:                           # Added labels section
    app: search
    namespace: 
spec:
  selector:
    app: search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: NodePort
